= Master's Thesis: Surrounding Environment Effects in Virtual Reality

This repository contains master's thesis text source files and assets. +
Source files of the implementation can be found in repositories
https://github.com/mmajko/openhvr-server[openhvr-server] and 
https://github.com/mmajko/openhvr-unity[openhvr-unity].

Title::
    Surrounding Environment Effects in Virtual Reality

School::
    Faculty of Information Technology +
    Czech Technical University in Prague

Department::
    Department of Software Engineering

Student::
    Bc. Marián Hlaváč

Supervisor::
    Ing. Jiří Chludil

Study Programme & Branch::
    Informatics, Web and Software Engineering

== Abstract

The thesis describes the process of creating a system used for
enhancing virtual reality with haptic feedback and other external effects.
The primary objective is to create an open and easily extendable software
for controlling multiple IoT devices, which works together 
to provide virtual reality users with effects synchronized with the
virtual world. The results also include software tools 
for developers, which allows them to create more immersive 
and believable virtual reality experiences. 

== Assignment

The goal is to create a part of a virtual reality system, which enhances the
experience in the virtual reality worlds with real-world effects, such as wind
or heat effects. The work is split into three parts — web-based room
configurator, server application, and Unity framework plug-in.

1. Research relevant electrical appliances and their capabilities, determine
    which of those are suitable for producing the effects and controlling
    programmatically from a computer.

2. Research and evaluate existing software solutions for the room configuration.

3. Using the typical software engineering methods, design the room configurator
    and methods of communication between devices and the server.

4. Implement the web-based room configurator, server application, and Unity
    framework plug-in.

5. Write unit tests, perform integration tests and user testing of the
    completed system.

== Table of Contents

* Introduction
* Virtual reality
** Contemporary hardware
** Uses of virtual reality
** Developing for virtual reality
* The current state of sensory feedback in virtual reality
** Experiments in sensory feedback
** Commercial products providing haptic feedback
* Existing solutions and Related work
** Related work
** Configurator tools
* Analytical evaluation of the system
** Assessment of human senses
** Viable electrical appliances
** Analysis of the appliances used
** Configurator Tool analysis
** Communication Server analysis
** Unity Plug-in analysis
** OpenHVR system analysis
** Means of communication analysis
* Proof of Concept
* System design
** Components cooperation
** Configurator Tool wireframe prototype
** REST API Design
** API Security
* Implementation
** Communication Server
** Configurator Tool
** Unity Plug-in
** Implementation notes
** Hardware used
** Results
* Example application using OpenHVR
** Testing entities
* User testing
** Devices property measuring
** Primary user test
* Conclusion
* Future works
* Bibliography
* Appendices
* List of Figures