== Future works

The main appeal for a follow-up work is to create an actual VR application
using the OpenHVR system practically. The example application presented in this
work is only for testing and presentation purposes and can't be considered as
full VR experience with enriched environmental effects.

It also might be interesting to think about configurable limitations of the
system by the administrator.
Some effects can consume a lot of electricity (especially space heaters)
and currently developers designing the effects aren't limited in how many
effects can be turned on at the same time and for how long.

{TODO} The direction test should be performed again and better, with ...

=== WebXR web configurator

WebXR capabilities could be incorporated into the Configurator Tool.
User would not need to use the Unity Helper for Configurator to accurately
mark positions of effect devices. He/she would see the room
size and properties in the Web Configurator directly and
in real-time. Using headset or just the controllers he would then define
the effect devices positions and rotations. On the other hand, the support in
browsers for WebXR is still very experimental (as of April 2020 <<webxr>>) and
most importantly, it is not certain that the space coordinate frame of
WebXR applications will be exactly the same as the space coordinate frame
of OpenVR or Oculus applications (to be used in Unity applications).

=== Service discovery

Unity Plug-in should be able to automatically discover the OpenHVR server.
This feature would mitigate the necessity to manually specify IP address
of computer with the running OpenHVR server instance. Such feature would
greatly enhance the user experience.
