name: Render thesis with LaTeX
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build book output files
    runs-on: ubuntu-latest
    container: marianhlavac/fit-ctu-thesis-texlive
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Prerender
      run: pdflatex DP_Hlavac_Marian_2020
    - name: Compose Bibliography with bibtex
      uses: bibtex DP_Hlavac_Marian_2020.aux
    - name: Final render
      run: pdflatex DP_Hlavac_Marian_2020
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v2
      with:
        name: master-thesis-hlavac-marian-2020
        path: DP_Hlavac_Marian_2020.pdf
    - name: Output build log to console
      run: cat DP_Hlavac_Marian_2020.log